# Generated by Django 4.1 on 2022-09-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
