# Generated by Django 4.1 on 2022-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmodel',
            name='review',
            field=models.TextField(),
        ),
    ]
